var questionData = [
  {
    text: "Combien de joueurs y a-t-il dans une équipe de football?",
    answer1: "5",
    answer2: "7",
    answer3: "11",
    answer4: "235",
    rightAnswer: 3,
  },
  {
    text: "Combien de temps la lumière du soleil met-elle pour nous parvenir?",
    answer1: "15 secondes",
    answer2: "8 minutes",
    answer3: "2 heures",
    answer4: "3 mois",
    rightAnswer: 2,
  },
  {
    text: "En 1582, le pape Grégoire XIII a décidé de réformer le calendrier instauré par Jules César. Mais quel était le premier mois du calendrier julien?",
    answer1: "Janvier",
    answer2: "Février",
    answer3: "Mars",
    answer4: "Avril",
    rightAnswer: 3,
  },
  {
    text: "Lequel de ces signes du zodiaque n'est pas un signe d'Eau?",
    answer1: "Le Verseau",
    answer2: "Le Cancer",
    answer3: "Le Scorpion",
    answer4: "Les Poissons",
    rightAnswer: 1,
  },
  {
    text: "Combien de doigts ai-je dans mon dos?",
    answer1: "2",
    answer2: "3",
    answer3: "4",
    answer4: "5, comme tout le monde",
    rightAnswer: 4,
  },
];
